### PR TITLE
Make presentedHint and variablesReference optional

### LINKED ISSUE #14: `EvaluateResponse` `presentedHint` should be optional
**Describe the bug**
This attribute is mandatory in the library but optional in the specs

https://github.com/codx-dev/dap-reactor/blob/d739d81b0999803106eb3b64ca43388d85d5d4af/src/models/evaluate.rs#L30

### PR DESCRIPTION
**Pull request by Daksh14**
**Describe the change**
Make presentedHint optional in evaluate.rs 

**Introduced tech-debts**
N/A

**Base issue**
Resolves #14 and #8

### CODE REVIEW

File: src/event/impls.rs [hunk 1]
```diff
@@ -295,10 +295,13 @@ impl Event {
                 let category = utils::attribute_string_optional("category", category);
                 let output = utils::attribute_string("output", output);
                 let group = utils::attribute_string_optional("group", group);
+                // UNWRAP: Okay because then clause only executes when the
+                // first argument is true. So in the then closure, it's not a None.
                 let variables_reference = utils::attribute_u32_optional(
                     "variablesReference",
-                    (variables_reference > 0).then_some(variables_reference),
+                    (variables_reference > Some(0)).then(|| variables_reference.unwrap()),
```
Comment (vlopes11) [inline src/event/impls.rs]: Instead of unwrap, I recommend using [filter](https://doc.rust-lang.org/std/option/enum.Option.html#method.filter) here

Example:
`variables_reference.filter(|r| r > &0)`

**Review by vlopes11 — CHANGES_REQUESTED** [review]

File: src/event/impls.rs [hunk 2]
```diff
@@ -295,10 +295,13 @@ impl Event {
                 let category = utils::attribute_string_optional("category", category);
                 let output = utils::attribute_string("output", output);
                 let group = utils::attribute_string_optional("group", group);
+                // UNWRAP: Okay because then clause only executes when the
+                // first argument is true. So in the then closure, it's not a None.
```
Comment (vlopes11) [inline src/event/impls.rs]: The remainder comment should probably be removed

**Review by vlopes11 — APPROVED** [review]
